export const ICONOS =
{
   email:"email",
   person:"person",
   call:"call",
   iconoContrasenia:{ abierto:"visibility",
  cerrado:"visibility_off"
 },
  home: 'home',
  tijera: 'content_cut',
  carita_feliz: 'sentiment_very_satisfied',
  calendario: 'event',
  dinero: 'payments',
  tarjeta: 'credit_card',
  perfil: 'account_circle',
  badge:'badge',
  eventNote:'event_note',
  star: 'star',
  people: 'people',
  settings: 'settings',
  logout: 'logout',
  lupa: 'search',
  reloj: 'schedule',
  ubicacion:'place',
  exclamacion:'priority_high',
  tilde:'check',
  flecha_creciendo:'trending_up',
  robot: 'smart_toy',

}
